"""user song genre

Revision ID: d21c2ec154d2
Revises: 
Create Date: 2020-05-04 22:24:07.015707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21c2ec154d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('user',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.String(length=64), nullable=False),
    sa.Column('middlename', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pk'),
    sa.UniqueConstraint('email')
    )
    op.create_table('song',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cover_image', sa.String(length=200), nullable=True),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('mp3_file', sa.String(length=200), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('listens', sa.Integer(), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['genre'], ['genre.pk'], ),
    sa.ForeignKeyConstraint(['user'], ['user.pk'], ),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('user')
    op.drop_table('genre')
    # ### end Alembic commands ###
